### ISSUE TITLE
Composer is 1.0, how to update

### ISSUE THREAD

**Issue by ikac5** [litespeedtech/lsws-magento-docker-env#2]
How to update the composer to 2.0 ?

**Comment by Code-Egg** [comment]
Right, composer 2.x works with Magento v2.4.2+ 
Just pushed a new version to the repository. 
Since you already installed it, can manually upgrade it from the litespeed container. 

`docker exec -it LITESPEED_CONTAINER_ID bash` 
```
php composer-setup.php --version 2.1.5
mv composer.phar /usr/local/bin/composer
composer -V
```

**Comment by ikac5** [comment]
Thanks is working.
One more thing, if I have already installed magento site via composer, not via git how to start ?
I copy in folder and try to open give me 404 error

**Comment by Code-Egg** [comment]
Glad to know it works. 
To answer this question I may need more information, did you "install the Magento via composer" by this lsws-magento-docker-env solution or something else? 
Also not sure what copy in a folder means, did you mean copy the Magento 2 into a folder?

**Comment by ikac5** [comment]
I make new directory in sites with name like the url of the site and in that folder I make html folder and in that I install magento via composer
https://devdocs.magento.com/guides/v2.4/install-gde/composer.html
than I add the domain with
bash bin/domain.sh [-D, --del] example.com

and when try to open usually is 404 or 500 error

**Comment by Code-Egg** [comment]
Ok, you mean install the Magento from the container right? 
I am not sure, need to check the server and config. If you want, please check LiteSpeed Web Admin virtual host template settings from GUI.

For the first Magento site setup, I'd recommend you just change the .env value and run demo site script. 
https://docs.litespeedtech.com/cloud/docker/magento/#starting-a-demo-site 

Or use all of our scripts to set up the domain, DB, and site for you. 
https://docs.litespeedtech.com/cloud/docker/magento/#creating-a-domain-and-virtual-host
```
bash bin/domain.sh -A example.com
bash bin/database.sh -D example.com
bash bin/appinstall.sh -A magento -D example.com
```

**Comment by ikac5** [comment]
Yes I install Magento via composer in container
there a problem in bash bin/appinstall.sh -A Magento -D example.com
I try to remove install_magento from appinstallctl.sh
but once again 
/var/www/vhosts/wagc.ls/html/.htaccess not exist, skip
/usr/local/bin/appinstallctl.sh: line 676: bin/magento: No such file or directory
and 404 error

.env.php file is ok

How to enter in Litespeed gui ?

**Comment by ikac5** [comment]
![image](https://user-images.githubusercontent.com/86470634/128541432-7b478cdb-4f76-47c8-b3ac-8c6192cddf55.png)
I make this change now is working

**Comment by Code-Egg** [comment]
HIHI,

Since you already have Magento installed manually, you should not use `bash bin/appinstall.sh -A Magento -D example.com`. It is for Magento installation. Please use `bash bin/domain.sh -A example.com` to create the domain and virtual host on LSWS instead.
