### ISSUE TITLE
Can be sites folder out of the repo ?

### ISSUE THREAD

**Issue by ikac5** [litespeedtech/lsws-magento-docker-env#3]
Sorry that I open like new issue, but I don't know how to communicate otherwise, what is yours email ?
The question is can be the sites folder outside your repository, this is necessary, because how to include our repo for site in your repo sites folder, only via like submodule, but it will be difficult to manage every day.

Thanks

**Comment by Code-Egg** [comment]
Hi,

I'm not really sure, you might want to change the path from docker-compose.yml. 
https://stackoverflow.com/questions/40905761/how-do-i-mount-a-host-directory-as-a-volume-in-docker-compose

You can find me on [golitespeed community](https://litespeedtech.com/slack/)

**Comment by ikac5** [comment]
Yes I done that, plus change some script in bin directory.
I put the docker repository like git subtree, but then have problem when I try to pull.
I need to have the docker repo plus my repo for the sites that are in development, any idea ?
If I push the docker repo only like copy I will lose ability to pull updates

**Comment by Code-Egg** [comment]
I don't have a good idea but [submodules](https://dev.to/jjokah/submodules-a-git-repo-inside-a-git-repo-36l9) like you said earlier. 
We can keep this issue open to see if any input from the public.

**Comment by ikac5** [comment]
I think I will solve, I put the ls docker repo like subtree, and make copy of the docker compose file.
When I started docker I use the option --project-directory, so far so good, but not sure that all scripts in bin folder is working.
Also this one command bash ls-docker/bin/database.sh -D example.com I don't know for what use is ?
I import database in the container

**Comment by Code-Egg** [comment]
Hi,
It's for creating a database, user name, and password for that domain. If you have your own DB, then this step can be skipped. 
https://docs.litespeedtech.com/cloud/docker/magento/#creating-a-database
